name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: sa-east-1
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}

      - name: Invoque CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{secrets.AWS_CODEDEPLOY_APPLICATION}} \
            --deployment-group-name ${{secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP}} \
            --description ${GITHUB_SHA} \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --ignore-application-stop-failures



